r"""
Build the data behind the project page (docs/index.html) from the pipeline's
own functions, so the page shows exactly what the scripts compute.

Writes docs/data/:
  synthetic.json            sample extent, truth trees, detections, headline metrics
  cloud.bin                 a subsample of the synthetic point cloud for the 3D view
                            (uint16 x, y, z, height-above-ground in decimetres, then uint8 class)
  density.json + density_<step>.png   CHM and detections at each thinning step
  stands.geojson            sheet L4132D stands with inventory vs LiDAR (if real data present)
  chm_2020.png + real.json  the 2020 canopy height model, warped to Web Mercator, and the
                            headline validation numbers
  machine.json              per-stand terrain flags (if machine_planning.csv is present)
  wa.json                   Washington FPA applications, from the committed snapshot

Runs after the synthetic track (needs data/nuuksio_dem.tif) and, for the real
sections, after fetch_open_data.py. Missing inputs skip their section.

Data: synthetic sample generated by generate_nuuksio.py; Suomen metsakeskus /
Finnish Forest Centre, CC BY 4.0; Washington DNR Forest Practices Applications.

    python build_web_data.py
"""
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import rasterio

OUT = Path("docs/data")
SEED = 7
CLOUD_POINTS = 320_000
DENSITY_STEPS = [13, 6, 3, 2, 1]        # the decimation steps density_study.py uses at 1 m


def r(x, n=2):
    return None if x is None or (isinstance(x, float) and not np.isfinite(x)) else round(float(x), n)


def ramp(h, hmax=36.0):
    """Canopy height -> RGBA: bare ground transparent-ish, then moss to lichen to pale crown."""
    stops = np.array([[0, 70, 62, 52], [3, 96, 112, 74], [12, 79, 110, 69],
                      [22, 132, 158, 98], [30, 196, 204, 150], [hmax, 238, 240, 214]], float)
    hh = np.clip(np.nan_to_num(h, nan=0.0), 0, hmax)
    rgb = np.stack([np.interp(hh, stops[:, 0], stops[:, k]) for k in (1, 2, 3)], axis=-1)
    a = np.where(np.isnan(h), 0, np.where(hh < 2, 90, 255))
    return np.dstack([rgb, a]).astype(np.uint8)


def save_png(rgba, path):
    from PIL import Image
    Image.fromarray(rgba, "RGBA").save(path, optimize=True)


# ------------------------------------------------------------------ synthetic

def synthetic():
    import laspy
    from detect_trees import match_to_truth
    import detect_trees as dt

    las = laspy.read("data/nuuksio_sample.laz")
    x, y, z = np.asarray(las.x), np.asarray(las.y), np.asarray(las.z)
    cls = np.asarray(las.classification).astype(np.uint8)
    x0, y0, z0 = float(x.min()), float(y.min()), float(z.min())

    with rasterio.open("data/nuuksio_dem.tif") as src:
        dem = src.read(1).astype(float)
        dem[dem == src.nodata] = np.nan
        if np.isnan(dem).any():                          # fill gaps from the nearest cell
            from scipy import ndimage
            idx = ndimage.distance_transform_edt(np.isnan(dem), return_distances=False, return_indices=True)
            dem = dem[tuple(idx)]
        rows, cols = rasterio.transform.rowcol(src.transform, x, y)
        rows = np.clip(rows, 0, dem.shape[0] - 1)
        cols = np.clip(cols, 0, dem.shape[1] - 1)
    hag = np.clip(z - dem[rows, cols], 0, None)

    rng = np.random.default_rng(SEED)
    keep = rng.choice(len(x), size=min(CLOUD_POINTS, len(x)), replace=False)
    keep.sort()
    dm = lambda a: np.clip(np.round(a * 10), 0, 65535).astype(np.uint16)
    block = np.column_stack([dm(x[keep] - x0), dm(y[keep] - y0), dm(z[keep] - z0), dm(hag[keep])])
    OUT.mkdir(parents=True, exist_ok=True)
    with open(OUT / "cloud.bin", "wb") as f:
        f.write(block.astype("<u2").tobytes())
        f.write(cls[keep].tobytes())

    truth = pd.read_csv(dt.TRUTH_PATH)
    chm, transform, _ = dt.load_chm()
    det = dt.detect_tops(chm, transform)
    det, tm = match_to_truth(det, truth)
    tp = int(tm["detected"].sum())
    err = (tm.loc[tm["detected"], "detected_height_m"] - tm.loc[tm["detected"], "height_m"])
    metrics = {"truth": len(tm), "detected": len(det), "tp": tp, "fp": len(det) - tp,
               "fn": len(tm) - tp, "recall": r(tp / len(tm) * 100, 1),
               "precision": r(tp / len(det) * 100, 1), "rmse": r((err ** 2).mean() ** 0.5),
               "by_species": {sp: r(tm.loc[tm.species == sp, "detected"].mean() * 100, 1)
                              for sp in ["spruce", "pine", "birch"]}}
    info = {
        "origin": [x0, y0, z0], "points_total": int(len(x)), "points_shown": int(len(keep)),
        "extent_m": [r(x.max() - x0, 1), r(y.max() - y0, 1)], "relief_m": r(z.max() - z0, 1),
        "density": r(len(x) / ((x.max() - x0) * (y.max() - y0)), 2),
        "metrics": metrics,
        "truth": [[r(t.x_tm35fin - x0, 1), r(t.y_tm35fin - y0, 1), r(t.ground_z - z0, 1), r(t.height_m, 1),
                   t.species[0], int(t.detected)] for t in tm.itertuples()],
        "detections": [[r(d.x_tm35fin - x0, 1), r(d.y_tm35fin - y0, 1), r(d.height_m, 1),
                        int(d.is_true_positive)] for d in det.itertuples()],
    }
    (OUT / "synthetic.json").write_text(json.dumps(info, separators=(",", ":")))
    print(f"synthetic: {len(keep):,} of {len(x):,} points, {len(det)} detections, "
          f"recall {metrics['recall']}%, precision {metrics['precision']}%, RMSE {metrics['rmse']} m")
    return x0, y0


def density(x0, y0):
    import density_study as ds
    truth = pd.read_csv(ds.TRUTH)
    n_pts, area, _, _ = ds.source_stats()
    rows = []
    for step in DENSITY_STEPS:
        ds.build_chm(step, 1.0)
        det = ds.detect(1.0)
        ev = ds.evaluate(det, truth)
        d2, tm = ds.match_to_truth(det, truth)
        with rasterio.open(ds.TMP_CHM) as src:
            chm = src.read(1).astype(float)
            chm[chm == src.nodata] = np.nan
            b = src.bounds
        save_png(ramp(chm), OUT / f"density_{step}.png")
        rows.append({
            "step": step, "density": r(n_pts / step / area, 2), "png": f"density_{step}.png",
            "bounds": [r(b.left - x0, 1), r(b.bottom - y0, 1), r(b.right - x0, 1), r(b.top - y0, 1)],
            "empty_pct": r(np.isnan(chm).mean() * 100, 1),
            "detected": ev["n_detected"], "tp": ev["tp"], "fp": ev["fp"], "fn": ev["fn"],
            "recall": r(ev["recall"] * 100, 1), "precision": r(ev["precision"] * 100, 1),
            "rmse": r(ev["height_rmse"]),
            "dets": [[r(d.x_tm35fin - x0, 1), r(d.y_tm35fin - y0, 1), int(d.is_true_positive)]
                     for d in d2.itertuples()],
            "missed": [[r(t.x_tm35fin - x0, 1), r(t.y_tm35fin - y0, 1)] for t in tm.itertuples() if not t.detected],
        })
        print(f"density step {step:>2}: {rows[-1]['density']:5.2f} p/m2  recall {rows[-1]['recall']}%  "
              f"precision {rows[-1]['precision']}%  RMSE {rows[-1]['rmse']} m  empty {rows[-1]['empty_pct']}%")
    Path(ds.TMP_CHM).unlink(missing_ok=True)
    res = pd.read_csv(ds.OUT_CSV) if Path(ds.OUT_CSV).exists() else None
    two_m = []
    if res is not None:
        for _, row in res[res.resolution_m == 2.0].sort_values("achieved_density").iterrows():
            two_m.append({"density": r(row.achieved_density), "recall": r(row.recall * 100, 1),
                          "precision": r(row.precision * 100, 1), "rmse": r(row.height_rmse),
                          "birch": r(row.recall_birch * 100, 1)})
        one_m = [{"density": r(row.achieved_density), "birch": r(row.recall_birch * 100, 1)}
                 for _, row in res[res.resolution_m == 1.0].sort_values("achieved_density").iterrows()]
    else:
        one_m = []
    (OUT / "density.json").write_text(json.dumps({"steps": rows, "two_m": two_m, "one_m_birch": one_m},
                                                 separators=(",", ":")))


# ----------------------------------------------------------------------- real

def real():
    import stand_validate as sv
    from rasterio.warp import calculate_default_transform, reproject, Resampling, transform_bounds
    if not Path(sv.GPKG).exists() or not (sv.TILE_DIR / f"CHM_{sv.SHEET}_2020.tif").exists():
        print("real: inputs missing, skipped")
        return
    gdf = sv.load_stands()
    chm, transform, bounds = sv.read_chm("2020")
    sub, _, _ = sv.analyse(gdf, chm, transform, bounds, 2020)

    v = sub[sub["usable_inv"] & sub["big_enough"] & sub["stemcount"].notna()
            & (sub["det_stems"] >= sv.MIN_STEMS)].copy()
    v["stem_ratio"] = v["det_stems_ha"] / v["stemcount"].clip(lower=1)
    dv = v[v["det_mean_h"].notna()]
    pool = sub[sub["eligible"]]
    by_cls = {}
    for cls, g in v.groupby("developmentclass"):
        if len(g) >= 5:
            by_cls[str(cls)] = {"n": len(g), "rate": r(100 * g["stem_ratio"].median(), 1)}
    summary = {
        "stands": len(sub), "private_ha": r(sub["poly_ha"].sum(), 0), "validated": len(v),
        "stem_recovery_median": r(100 * v["stem_ratio"].median(), 1),
        "inv_stems_median": r(v["stemcount"].median(), 0),
        "det_h_bias": r((dv["det_mean_h"] - dv["meanheight"]).mean()),
        "det_h_r": r(dv[["det_mean_h", "meanheight"]].corr().iloc[0, 1], 3),
        "chm_h_bias": r((dv["chm_mean_h"] - dv["meanheight"]).mean()),
        "chm_h_r": r(dv[["chm_mean_h", "meanheight"]].corr().iloc[0, 1], 3),
        "det_h_mean": r(dv["det_mean_h"].mean()), "inv_h_mean": r(dv["meanheight"].mean()),
        "by_class": by_cls,
        "pool": len(pool), "pool_cut": int(pool["op_cut"].sum()),
        "low_coverage": int((sub["coverage_pct"] < 50).sum()),
    }
    (OUT / "real.json").write_text(json.dumps(summary, indent=1))
    print("real:", json.dumps(summary))

    # stands for the map
    in_v = set(v["standid"])
    keep = ["standid", "developmentclass", "poly_ha", "meanheight", "det_mean_h", "chm_mean_h",
            "stemcount", "det_stems_ha", "coverage_pct", "op_cut", "restricted", "dom_species", "obs_year"]
    g = sub[keep + ["geometry"]].copy()
    g["validated"] = g["standid"].isin(in_v).astype(int)
    g["geometry"] = g.geometry.simplify(2.0)
    g = g.to_crs(4326)
    for c in keep:
        if g[c].dtype.kind == "f":
            g[c] = g[c].round(2)
    g = g.rename(columns={"developmentclass": "cls", "poly_ha": "ha", "meanheight": "inv_h",
                          "det_mean_h": "det_h", "chm_mean_h": "chm_h", "stemcount": "inv_n",
                          "det_stems_ha": "det_n", "coverage_pct": "cov", "dom_species": "sp",
                          "obs_year": "obs"})
    (OUT / "stands.geojson").write_text(g.to_json(drop_id=True, na="null"))
    print(f"real: {len(g)} stands -> stands.geojson")

    # the 2020 CHM, warped to Web Mercator for the map
    src_crs = "EPSG:3067"
    h, w = chm.shape
    left, bottom, right, top = bounds
    factor = 3
    small = chm[: h - h % factor, : w - w % factor].reshape(h // factor, factor, w // factor, factor)
    small = np.nanmax(small, axis=(1, 3))
    st = rasterio.transform.from_bounds(left, top - (h - h % factor), left + (w - w % factor), top,
                                        small.shape[1], small.shape[0])
    dt, dw, dh = calculate_default_transform(src_crs, "EPSG:3857", small.shape[1], small.shape[0],
                                             *rasterio.transform.array_bounds(*small.shape, st))
    out = np.full((dh, dw), np.nan, np.float32)
    reproject(small.astype(np.float32), out, src_transform=st, src_crs=src_crs, dst_transform=dt,
              dst_crs="EPSG:3857", resampling=Resampling.nearest, src_nodata=np.nan, dst_nodata=np.nan)
    save_png(ramp(out), OUT / "chm_2020.png")
    wb = transform_bounds("EPSG:3857", "EPSG:4326", *rasterio.transform.array_bounds(dh, dw, dt))
    summary["chm_bounds"] = [r(wb[1], 6), r(wb[0], 6), r(wb[3], 6), r(wb[2], 6)]   # S, W, N, E
    (OUT / "real.json").write_text(json.dumps(summary, indent=1))
    print(f"real: chm_2020.png {dw} x {dh}")


def machine():
    p = Path("data/machine_planning.csv")
    if not p.exists():
        print("machine: no machine_planning.csv, skipped")
        return
    df = pd.read_csv(p)
    sched = df[(df["devclass"].astype(str).str.zfill(2) == "04") & (df["op_cut"] == 1)]
    out = {"scheduled": len(sched),
           "season": sched["season"].value_counts().to_dict(),
           "access": sched["access"].value_counts().to_dict(),
           "both": int(((sched["season"] != "summer-trafficable") & (sched["access"] != "conventional")).sum()),
           "stands": {str(int(s.standid)): [s.season, s.access, r(s.slope_mean, 1), r(s.wet_frac * 100, 0),
                                            r(s.steep_frac * 100, 0)] for s in sched.itertuples()}}
    (OUT / "machine.json").write_text(json.dumps(out, separators=(",", ":")))
    print("machine:", {k: out[k] for k in ("scheduled", "season", "access", "both")})


def wa():
    a = pd.read_csv("data/wa_fpa/fpa_slope_by_application.csv")
    out = {"source": "committed snapshot, data/wa_fpa/fpa_slope_by_application.csv",
           "apps": [[r(s, 1), int(f == "Y")] for s, f in zip(a["slope_max"], a["flag"])]}
    (OUT / "wa.json").write_text(json.dumps(out, separators=(",", ":")))
    print(f"wa: {len(a)} applications, {100 * (a.flag == 'Y').mean():.1f}% flagged")


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    x0, y0 = synthetic()
    density(x0, y0)
    real()
    machine()
    wa()
    return 0


if __name__ == "__main__":
    sys.exit(main())
