[workspace]
authors = ["brooksg <brooksg@zillowgroup.com>"]
channels = ["conda-forge"]
name = "lidar-explore"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
python-pdal = ">=3.5.5,<4"
laspy = ">=2.7.0,<3"
rasterio = ">=1.5.1,<2"
geopandas = ">=1.1.4,<2"
numpy = ">=2.5.2,<3"
scipy = ">=1.18.0,<2"
matplotlib = ">=3.11.1,<4"
lazrs-python = ">=0.8.2,<0.9"
snowflake-connector-python = ">=4.7.1,<5"
